on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: cool
        uses: bertg/cool-action@v1.2
      - name: Get the output
        run: echo "The output was ${{ steps.cool.outputs.a_cool_emoji }}"
